version: '3.4'

services:
  node:
    image: bayulobi/cicd
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000