version: "3.7"

services:
  cicd:
    image: bayulobi/cicd
    build:
      context: .
      dockerfile: ./Dockerfile
    
    environment:
     NODE_ENV: development

    ports: 
      - 3000:3000
      - 2000:2000
    command: ["node", "--inspect=0.0.0.0:2000", "app.js"]
    