name: Push cli

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Use Node.js 18
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'

        - name: Install Dependencies
          run: npm install

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          
        - name: Build and Push
          id: docker_build
          uses: docker/build-push-action@v5
          with:
           push: true
           tags: bayulobi/cicd:latest

        - name: Login SSH and Deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            debug: true
            script:
              cd /home/bayulobi/belajar-cicd
              git config pull.rebase true
              git pull origin main
              docker compose -f docker-compose.yml down
              docker pull bayulobi/cicd-demo
              docker compose -f docker-compose.ymp up -d
       